### ISSUE TITLE
Slow opening of MD files, even in Editor mode

### ISSUE THREAD

**Issue by jonathanlermitage** [4ch1m/github-markdown-emojis#2]
First, I would like to thank you for your excellent plugin!

The issue: when I open a markdown file (double-click on a md file in the Project view), it takes something like 0.5s or 1 second. Without this plugin, this is instant.  
My understanding is that it is normal for markdown files opened in Preview mode, or in mixed mode (Editor + Preview). -> I am wondering if something can be improved for markdown files opened in Editor mode directly.  
I tried to find some info in the JetBrains SDK documentation, but I only have a limited experience with the code editor API.  
This is not a critical issue, and again, your plugin is really good ;-)

Tested with IntelliJ Ultimate 2023.1.1 and PyCharm Community 2023.1, on Windows 10.  
Markdown files with and without emojis.

**Comment by 4ch1m** [comment]
Hi there,

Thanks for the feedback.

> it takes something like 0.5s or 1 second

What exactly do you mean with this?
Does is take a second until the preview pane itself is visible?
Does it take a second for the emojis to get replaced/rendered?

I've been using the plugin myself for quite a while now (... obviously :smile:).
I didn't experience any noticeable lag or other performance regression regarding the appearance/usage of the preview pane.

The delay for all emojis being rendered is by design.

Check the source code here: [GitHubMarkdownEmojis.kt](https://github.com/4ch1m/github-markdown-emojis/blob/58143a6e29b8862671230ef08c88f4629c356b05/src/main/kotlin/de/achimonline/github_markdown_emojis/GitHubMarkdownEmojis.kt)

That's because we have to wait until all content of the preview pane is available for inspection (and as of now there is no API hook available for that).
We also have have to re-render/re-evaluate everything in a loop since the content will change according to the file being edited.

If you have any suggestions or concrete hints on how to improve the code, I'd be happy to integrate your pull-request.

**Comment by jonathanlermitage** [comment]
There is a lag when opening a md file, even if the IDE is configured to open them in Editor mode (no preview). So, when I double-click on a md file, nothing happens during 0.5~1s, then the editor opens the file in a tab.

**Comment by 4ch1m** [comment]
> There is a lag when opening a md file, even if the IDE is configured to open them in Editor mode (no preview). So, when I double-click on a md file, nothing happens during 0.5~1s, then the editor opens the file in a tab.

Hmmm... so the editor itself is opening with a delay?! :thinking: 
That's strange.

I just tried to reproduce this on my machine; but I don't notice any difference.

Do you have any other plugins installed?
Could you try to run the plugin within a fresh installation? (Or simply run it with the Gradle task 'runIde' of this project.)

I will keep an eye on this and try to reproduce it.
Please also let me know if you find anything on your end.

Thanks!
